In [16]:
import pandas as pd
from IPython.display import display, HTML
from ipywidgets import interact, widgets, VBox, HBox

In [17]:
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

# Generate table headers
headers = "".join([f"<th>{col}</th>" for col in df.columns])

# Generate table rows
rows = ""
for row in df.itertuples(index=False):
    rows += "<tr>" + "".join([f"<td>{cell}</td>" for cell in row]) + "</tr>"

In [18]:
df.style.to_html()

'<style type="text/css">\n</style>\n<table id="T_840e8">\n  <thead>\n    <tr>\n      <th class="blank level0" >&nbsp;</th>\n      <th id="T_840e8_level0_col0" class="col_heading level0 col0" >Name</th>\n      <th id="T_840e8_level0_col1" class="col_heading level0 col1" >Age</th>\n      <th id="T_840e8_level0_col2" class="col_heading level0 col2" >City</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id="T_840e8_level0_row0" class="row_heading level0 row0" >0</th>\n      <td id="T_840e8_row0_col0" class="data row0 col0" >Alice</td>\n      <td id="T_840e8_row0_col1" class="data row0 col1" >25</td>\n      <td id="T_840e8_row0_col2" class="data row0 col2" >New York</td>\n    </tr>\n    <tr>\n      <th id="T_840e8_level0_row1" class="row_heading level0 row1" >1</th>\n      <td id="T_840e8_row1_col0" class="data row1 col0" >Bob</td>\n      <td id="T_840e8_row1_col1" class="data row1 col1" >30</td>\n      <td id="T_840e8_row1_col2" class="data row1 col2" >Los Angeles</td>\n    </tr>\n    <tr>\n      <th id="T_840e8_level0_row2" class="row_heading level0 row2" >2</th>\n      <td id="T_840e8_row2_col0" class="data row2 col0" >Charlie</td>\n      <td id="T_840e8_row2_col1" class="data row2 col1" >35</td>\n      <td id="T_840e8_row2_col2" class="data row2 col2" >Chicago</td>\n    </tr>\n    <tr>\n      <th id="T_840e8_level0_row3" class="row_heading level0 row3" >3</th>\n      <td id="T_840e8_row3_col0" class="data row3 col0" >David</td>\n      <td id="T_840e8_row3_col1" class="data row3 col1" >40</td>\n      <td id="T_840e8_row3_col2" class="data row3 col2" >Houston</td>\n    </tr>\n  </tbody>\n</table>\n'

In [19]:
class data_class(pd.DataFrame):
    def __init__(self, data):
        super().__init__(data)

    def _format_html(self, text, completed):
        pass
        
    def _repr_html_(self):
        return """<table>
                  <tr>
                    <td>
                      <table>
                        <tr><th>First name</th></tr>
                        <tr><td>David</td></tr>
                        <tr><td>Frank</td></tr>
                        <tr><td>Bob</td></tr>
                      </table>
                    </td>
                
                    <td>
                      <table>
                        <tr><th>Last name</th></tr>
                        <tr><td>David</td></tr>
                        <tr><td>Frank</td></tr>
                        <tr><td>Bob</td></tr>
                      </table>
                    </td>
                
                    <td>
                      <table>
                        <tr><th>Third name</th></tr>
                        <tr><td>David</td></tr>
                        <tr><td>Frank</td></tr>
                        <tr><td>Bob</td></tr>
                      </table>
                    </td>
                    
                  </tr>
                </table>"""

In [20]:
data_class(data)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [21]:
# Function to render DataFrame as an interactive DataTable
def render_dataframe_as_datatable(df):
    html = """
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function() {{
            $('#dataframe').DataTable({{}});
        }});
    </script>
    <table id="dataframe" class="display" style="width:100%">
        <thead>
            <tr>
                {headers}
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    """

    # Generate table headers
    headers = "".join([f"<th>{col}</th>" for col in df.columns])

    # Generate table rows
    rows = ""
    for row in df.itertuples(index=False):
        rows += "<tr>" + "".join([f"<td>{cell}</td>" for cell in row]) + "</tr>"

    # Format the HTML with the generated table
    html = html.format(headers=headers, rows=rows)
    display(HTML(html))

# Call the function to display the DataFrame as a DataTable
render_dataframe_as_datatable(df)

In [22]:
pandas_html = """<style type="text/css">\n</style>\n<table id="T_7b19f">\n  <thead>\n    <tr>\n      <th class="blank level0" >&nbsp;</th>\n      <th id="T_7b19f_level0_col0" class="col_heading level0 col0" >Name</th>\n      <th id="T_7b19f_level0_col1" class="col_heading level0 col1" >Age</th>\n      <th id="T_7b19f_level0_col2" class="col_heading level0 col2" >City</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id="T_7b19f_level0_row0" class="row_heading level0 row0" >0</th>\n      <td id="T_7b19f_row0_col0" class="data row0 col0" >Alice</td>\n      <td id="T_7b19f_row0_col1" class="data row0 col1" >25</td>\n      <td id="T_7b19f_row0_col2" class="data row0 col2" >New York</td>\n    </tr>\n    <tr>\n      <th id="T_7b19f_level0_row1" class="row_heading level0 row1" >1</th>\n      <td id="T_7b19f_row1_col0" class="data row1 col0" >Bob</td>\n      <td id="T_7b19f_row1_col1" class="data row1 col1" >30</td>\n      <td id="T_7b19f_row1_col2" class="data row1 col2" >Los Angeles</td>\n    </tr>\n    <tr>\n      <th id="T_7b19f_level0_row2" class="row_heading level0 row2" >2</th>\n      <td id="T_7b19f_row2_col0" class="data row2 col0" >Charlie</td>\n      <td id="T_7b19f_row2_col1" class="data row2 col1" >35</td>\n      <td id="T_7b19f_row2_col2" class="data row2 col2" >Chicago</td>\n    </tr>\n    <tr>\n      <th id="T_7b19f_level0_row3" class="row_heading level0 row3" >3</th>\n      <td id="T_7b19f_row3_col0" class="data row3 col0" >David</td>\n      <td id="T_7b19f_row3_col1" class="data row3 col1" >40</td>\n      <td id="T_7b19f_row3_col2" class="data row3 col2" >Houston</td>\n    </tr>\n  </tbody>\n</table>\n"""

In [23]:
# Function to render DataFrame as an interactive DataTable
def render_dataframe_as_datatable(df):
    html = """
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function() {{
            $('#dataframe').DataTable({{}});
        }});
    </script>
<table>
  <tr>
    <td>
      <table>
        <tr><th>First name</th></tr>
        <tr><td>David</td></tr>
        <tr><td>Frank</td></tr>
        <tr><td>Bob</td></tr>
      </table>
    </td>

    <td>
      <table>
        <tr><th>Last name</th></tr>
        <tr><td>David</td></tr>
        <tr><td>Frank</td></tr>
        <tr><td>Bob</td></tr>
      </table>
    </td>

    <td>
      <table>
        <tr><th>Third name</th></tr>
        <tr><td>David</td></tr>
        <tr><td>Frank</td></tr>
        <tr><td>Bob</td></tr>
      </table>
    </td>
    
  </tr>
</table>
    """

    # Generate table headers
    headers = "".join([f"<th>{col}</th>" for col in df.columns])

    # Generate table rows
    rows = ""
    for row in df.itertuples(index=False):
        rows += "<tr>" + "".join([f"<td>{cell}</td>" for cell in row]) + "</tr>"

    # Format the HTML with the generated table
    html = html.format(headers=headers, rows=rows)
    display(HTML(html))

# Call the function to display the DataFrame as a DataTable
render_dataframe_as_datatable(df)

In [24]:
mytable = """<table id="table_id">
                <thead>
                    <tr>
                        {headers}
                    </tr>
                </thead>
            </table>
<link href="https://www.unpkg.com/dt_for_itables/dt_bundle.css" rel="stylesheet">
<script type="module">
    import {{DataTable, jQuery as $}} from 'https://www.unpkg.com/dt_for_itables/dt_bundle.js';

        document.querySelectorAll("#table_id:not(.dataTable)").forEach(table => {{
        // Define the table data
        const data = [];

        // Define the dt_args
        let dt_args = {{}};
        dt_args["data"] = data;

        // [pre-dt-code]
        new DataTable(table, dt_args);
    }});
</script>
""" 

# Format the HTML with the generated table
mytable = mytable.format(headers=headers)
display(HTML(mytable))

In [25]:
# Function to render DataFrame with column selection checkboxes above each column
def render_dataframe_with_column_selection(df):
    # Generate the HTML structure
    html = """
    <style>
        .checkbox-container {{
            text-align: center;
            margin-bottom: 5px;
        }}
        .hidden-column {{
            display: none;
        }}
        table.dataframe {{
            width: 100%;
            border-collapse: collapse;
        }}
        table.dataframe th, table.dataframe td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}
        table.dataframe th {{
            background-color: #f2f2f2;
        }}
    </style>
    <table id="dataframe" class="dataframe">
        <thead>
            <tr>
                {checkboxes}
            </tr>
            <tr>
                {headers}
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    <script>
        function toggleColumnVisibility(checkbox, colIndex) {{
            var table = document.getElementById('dataframe');
            var th = table.querySelectorAll('th:nth-child(' + (colIndex + 1) + ')');
            var td = table.querySelectorAll('td:nth-child(' + (colIndex + 1) + ')');
            for (var i = 0; i < th.length; i++) {{
                th[i].style.display = checkbox.checked ? '' : 'none';
            }}
            for (var i = 0; i < td.length; i++) {{
                td[i].style.display = checkbox.checked ? '' : 'none';
            }}
        }}
    </script>
    """

    # Generate checkboxes for each column in the header row
    checkboxes = "".join(
        [f'<th class="checkbox-container"><input type="checkbox" checked onclick="toggleColumnVisibility(this, {i})"></th>'
         for i, _ in enumerate(df.columns)]
    )

    # Generate table headers
    headers = "".join([f"<th>{col}</th>" for col in df.columns])

    # Generate table rows
    rows = ""
    for row in df.itertuples(index=False):
        rows += "<tr>" + "".join([f"<td>{cell}</td>" for cell in row]) + "</tr>"

    # Format the HTML with the generated content
    html = html.format(checkboxes=checkboxes, headers=headers, rows=rows)
    
    # Display the HTML in the Jupyter Notebook
    display(HTML(html))

# checkboxes: [Bool], each column selection
# @interact(checkboxes) 
# def update(html):
#     ## Clean
#     pass
#     ## Display again
#     display(HTML(html))
    
# Call the function to display the DataFrame with column selection
render_dataframe_with_column_selection(df)

In [26]:
# Function to render the DataFrame and handle column selection
def render_dataframe_with_column_selection(df):
    # Generate checkboxes for each column
    checkboxes = [widgets.Checkbox(value=False, description=col) for col in df.columns]

    # Create a button to generate the selected columns
    button = widgets.Button(description="Generate")

    # Output widget to display the selected columns
    output = widgets.Output()

    # Function to handle button click event
    def on_button_click(b):
        selected_columns = [cb.description for cb in checkboxes if cb.value]
        output.clear_output()
        with output:
            display(f"Selected columns: {selected_columns}")
        # Returning the selected columns to the original Python context
        return selected_columns

    # Bind the button click event to the function
    button.on_click(on_button_click)

    # Display the checkboxes and button
    display(widgets.VBox(checkboxes + [button, output]))

# Call the function to display the DataFrame with column selection
render_dataframe_with_column_selection(df)

VBox(children=(Checkbox(value=False, description='Name'), Checkbox(value=False, description='Age'), Checkbox(v…

In [27]:
# Global variable to store selected columns
selected_columns = []

# Function to render the DataFrame with column selection
def render_dataframe_with_column_selection(df):
    global selected_columns
    
    # Generate checkboxes for each column
    checkboxes = [widgets.Checkbox(value=True, description='', layout=widgets.Layout(width='auto')) for _ in df.columns]
    
    # Create labels for column names
    labels = [widgets.Label(value=col, layout=widgets.Layout(width='auto', margin='0 0 10px 0')) for col in df.columns]
    
    # Combine checkboxes and labels in a horizontal box layout
    checkbox_row = HBox([VBox([checkboxes[i], labels[i]]) for i in range(len(df.columns))])
    
    # Create a button to generate the selected columns
    button = widgets.Button(description="Generate")
    
    # Output widget to display the selected columns
    output = widgets.Output()
    
    # Convert the DataFrame to an HTML table to display
    html_df = widgets.HTML(value=df.to_html(index=False))

    # Function to handle button click event
    def on_button_click(b):
        selected_columns = [df.columns[i] for i in range(len(checkboxes)) if checkboxes[i].value]
        output.clear_output()
        with output:
            display(f"Selected columns: {selected_columns}")
            # return selected_columns
    
    # Bind the button click event to the function
    button.on_click(on_button_click)
    
    # Display the checkbox row, DataFrame, button, and output
    display(VBox([checkbox_row, html_df, button, output]))

# Call the function to display the DataFrame with column selection
render_dataframe_with_column_selection(df)

VBox(children=(HBox(children=(VBox(children=(Checkbox(value=True, layout=Layout(width='auto')), Label(value='N…

# Pré final version

### Render HTML

In [28]:
# Function to render DataFrame with checkboxes and a "Generate" button
def render_dataframe_with_column_selection(df):
    # Generate the HTML structure
    html = """
    <style>
        .checkbox-container {{
            text-align: center;
            margin-bottom: 5px;
        }}
        table.dataframe {{
            width: 100%;
            border-collapse: collapse;
        }}
        table.dataframe th, table.dataframe td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}
        table.dataframe th {{
            background-color: #f2f2f2;
        }}
    </style>
    <div>
        <table id="dataframe" class="dataframe">
            <thead>
                <tr>
                    {checkboxes}
                </tr>
                <tr>
                    {headers}
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
        <button onclick="generateSelectedColumns()">Generate</button>
    </div>
    <script>
        function generateSelectedColumns() {{
            var selectedColumns = [];
            var checkboxes = document.querySelectorAll('.checkbox-container input[type=checkbox]');
            for (var i = 0; i < checkboxes.length; i++) {{
                if (checkboxes[i].checked) {{
                    selectedColumns.push(checkboxes[i].getAttribute('data-colname'));
                }}
            }}
            var pySelectedColumns = JSON.stringify(selectedColumns);
            var code = "selected_columns = " + pySelectedColumns;
            var kernel = IPython.notebook.kernel;
            kernel.execute(code);
        }}
    </script>
    """

    # Generate checkboxes for each column in the header row
    checkboxes = "".join(
        [f'<th class="checkbox-container"><input type="checkbox" data-colname="{col}" checked></th>'
         for col in df.columns]
    )

    # Generate table headers
    headers = "".join([f"<th>{col}</th>" for col in df.columns])

    # Generate table rows
    rows = ""
    for row in df.itertuples(index=False):
        rows += "<tr>" + "".join([f"<td>{cell}</td>" for cell in row]) + "</tr>"

    # Format the HTML with the generated content
    html = html.format(checkboxes=checkboxes, headers=headers, rows=rows)
    
    # Display the HTML in the Jupyter Notebook
    display(HTML(html))

# Call the function to display the DataFrame with column selection
render_dataframe_with_column_selection(df)

# This variable will store the selected columns after the "Generate" button is clicked
selected_columns = []

### Ipywidgets

In [29]:
import pandas as pd
from IPython.display import display
from ipywidgets import widgets, VBox, HTML

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

# Global variables to store selected columns
selected_columns = {"Column 1": None, "Column 2": None}

# Function to render the DataFrame with column selection
def render_dataframe_with_column_selection(df):
    global selected_columns
    
    # Create dropdown widgets for column selection
    dropdown1 = widgets.Dropdown(
        options=tuple(df.columns),
        value=df.columns[0],
        description='Column 1',
        disabled=False
    )
    
    dropdown2 = widgets.Dropdown(
        options=tuple(df.columns),
        value=df.columns[1],
        description='Column 2',
        disabled=False
    )
    
    # Create a button to generate the selected columns
    button = widgets.Button(description="Generate")
    
    # Output widget to display the selected columns
    output = widgets.Output()
    
    # Convert the DataFrame to an HTML table
    html_df = df.to_html(index=False, classes='dataframe', border=0)

    # Define the CSS for table alignment
    css = """
    <style>
    .dataframe {
        border-collapse: collapse;
        width: 100%;
    }
    .dataframe th, .dataframe td {
        border: 1px solid #ddd;
        padding: 8px;
    }
    .dataframe th {
        background-color: #f2f2f2;
        text-align: center;
    }
    </style>
    """
    
    # Combine CSS and HTML table
    html_content = widgets.HTML(value=css + html_df)
    
    # Function to handle button click event
    def on_button_click(b):
        global selected_columns
        selected_columns["Column 1"] = dropdown1.value
        selected_columns["Column 2"] = dropdown2.value
        output.clear_output()
        with output:
            display(f"Selected columns: {selected_columns}")
    
    # Bind the button click event to the function
    button.on_click(on_button_click)
    
    # Display the dropdowns, HTML table (as a widget), button, and output
    display(VBox([dropdown1, dropdown2, html_content, button, output]))

# Call the function to display the DataFrame with column selection
render_dataframe_with_column_selection(df)

VBox(children=(Dropdown(description='Column 1', options=('Name', 'Age', 'City'), value='Name'), Dropdown(descr…

In [30]:
selected_columns

{'Column 1': None, 'Column 2': None}